spring:
  profiles:
    active: live
  application:
    name: sinsahelper-backend
  config:
    import: optional:configserver:http://ec2-13-124-25-31.ap-northeast-2.compute.amazonaws.com:88

  cloud:
    config:
      label: develop