name: Manual workflow

on:
  push:
    branches: master
  pull_request:
    branches: master

# jobs -> [jobA,jobB,jobC] -> steps -> [stepA,stepB,stepC]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
      
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin # check
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Execute Gradle build
      run: ./gradlew clean build --exclude-task test
    - name: save .jar file
      uses: actions/upload-artifact@v3
      with:
        name: jarfile
        path: ./build/libs/sinsahelper-0.0.1-SNAPSHOT.jar
      
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: download .jar file
      uses: actions/download-artifact@v3
      with:
        name: jarfile
        path: ./build/libs/sinsahelper-0.0.1-SNAPSHOT.jar
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: squib0612/sinsahelper-backend:latest
