name: Manual workflow

on:
  push:
    branches: master
  pull_request:
    branches: master

# jobs -> [jobA,jobB,jobC] -> steps -> [stepA,stepB,stepC]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./apps
    
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
      
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin # check
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Execute Gradle build
      run: ./gradlew clean build --exclude-task test
      env:
        working-directory: ./apps
      
  
  docker:
    runs-on: ubuntu-latest
    needs: build
    env:
      working-directory: ./apps
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: log
      run: pwd
      env:
        working-directory: ./apps
    - name: build image
      run: docker build -t squib0612/sinsahelper-backend:latest .
      env:
        working-directory: ./apps
    - name: push image to hub
      run: docker push squib0612/sinsahelper-backend:latest
      env:
        working-directory: ./apps
