name: CI/CD

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Checkout
      uses: actions/checkout@v3
      
    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Execute Gradle build
      run: ./gradlew clean build --exclude-task test
             
    - name: Docker build
      run: |
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          sudo docker build -t ${{ secrets.PROJECT_NAME }} .
          sudo docker tag ${{ secrets.PROJECT_NAME }} ${{ secrets.DOCKER_HUB_REPO }}:${GITHUB_SHA::7}
          sudo docker push ${{ secrets.DOCKER_HUB_REPO }}:${GITHUB_SHA::7}
          
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
            sudo docker pull ${{ secrets.DOCKER_HUB_REPO }}:${GITHUB_SHA::7}
            sudo docker tag ${{ secrets.DOCKER_HUB_REPO }}:${GITHUB_SHA::7} ${{ secrets.PROJECT_NAME }}
            sudo docker stop ${{ secrets.PROJECT_NAME }}
            sudo docker rm ${{ secrets.PROJECT_NAME }}
            sudo docker run -d --name ${{secrets.PROJECT_NAME }} -p 80:8080 ${{ secrets.PROJECT_NAME }}
            sudo docker image prune -f
    
